apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  # these are replica set labels
  labels:
    purpose: ingress-demo
    project: robomart
    app: app2
spec:
  replicas: 2
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: ingress-demo
      project: robomart
      app: app2
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: ingress-demo
        project: robomart
        app: app2
    spec:
      containers:
      - name: app2
        image: azharmd/app2:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    purpose: ingress-demo
    project: robomart
    app: app2
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/group.name: robomart
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: "app2.azharprojects.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80